Imported scenario keeps the status / scheduling
OpenBAS-Platform/openbas pull request #1050
Opened 2024-06-05 08:00 UTC by RomuDeuxfois

### Related issues

* https://github.com/OpenBAS-Platform/openbas/issues/903

2024-06-05 19:22 UTC, Christian-DONGMO requested changes

2024-06-05 19:22 UTC, Christian-DONGMO commented on openbas-api/src/main/java/io/openbas/service/ScenarioService.java
You should also split the exportScenario method into smaller methods

2024-06-07 08:49 UTC, RomuDeuxfois commented on openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java
I dit this part

2024-06-07 08:49 UTC, RomuDeuxfois commented on openbas-api/src/main/java/io/openbas/service/ScenarioService.java
It will be in another step

2024-06-10 08:49 UTC, Christian-DONGMO approved these changes

2024-06-10 08:50 UTC, Christian-DONGMO commented
Nice, Just remember to rebase

2024-06-10 12:14 UTC, merged