[backend] Fix on get exercise details to have better performance
OpenBAS-Platform/openbas pull request #1059
Opened 2024-06-06 13:05 UTC by Dimfacion

### Proposed changes

* Fix on get exercise details to have better performance
*

### Related issues

*
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-06-07 12:56 UTC, Christian-DONGMO requested changes

2024-06-07 13:21 UTC, Dimfacion commented on openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseDetails.java
> +  private Exercise.STATUS status;
Makes sense :) Done 👍

2024-06-07 13:42 UTC, Dimfacion commented on openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java
First point is done. Thanks for bringing this up :)

As for the second one, while I do agree on the idea, I don't think this should be the focus of the team right now and especially not in this fix. I'm okay with small improvments like the use of lombok but not with architectural changes in fixes.

2024-06-07 16:06 UTC, Christian-DONGMO approved these changes

2024-06-11 15:26 UTC, Dimfacion commented on openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseDetails.java
> +  @JsonProperty("exercise_logo_dark")
Removed

2024-06-11 15:26 UTC, Dimfacion commented on openbas-api/src/main/java/io/openbas/rest/exercise/form/ExerciseDetails.java
> +  @JsonProperty("exercise_logo_light")
Removed

2024-06-11 16:33 UTC, Dimfacion commented on openbas-api/src/main/java/io/openbas/rest/exercise/ExerciseApi.java
>    @PreAuthorize("isExerciseObserver(#exerciseId)")
Done

2024-06-12 06:47 UTC, RomuDeuxfois approved these changes

2024-06-12 07:07 UTC, merged