[Frontend]Fix alignment of platform icons in add assets to inject
OpenBAS-Platform/openbas pull request #1117
Opened 2024-06-19 09:05 UTC by johanah29

#1100

2024-06-19 09:06 UTC, johanah29 commented
![image](https://github.com/OpenBAS-Platform/openbas/assets/49673066/15839c5e-3143-461a-bee0-617147c65833)

2024-06-20 08:01 UTC, RomuDeuxfois requested changes

2024-06-20 08:01 UTC, RomuDeuxfois commented on openbas-front/src/admin/components/assets/endpoints/EndpointsDialogAdding.tsx
> +                            <PlatformIcon platform={endpoint.endpoint_platform} width={20} position={'relative'} marginRight={10} top={5} /> {endpoint.endpoint_platform}
This component should be atomic.
So, if the component itself is not align (text + icon), it should be changed directly in this component <Platform Icon />

if this is the case, then it is the parent component that must manage to align the interior of this component
Via a display: flex and align-items: center for example.

2024-07-05 11:43 UTC, RomuDeuxfois commented
No activity for more than 10 days ...

2024-07-09 11:21 UTC, RomuDeuxfois approved these changes

2024-07-09 11:21 UTC, merged