Issue/collector frontend errors
OpenBAS-Platform/openbas pull request #1959
Opened 2024-11-29 15:25 UTC by savacano28

### Proposed changes

*
*

### Related issues

* Closes #ISSUE-NUMBER
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2025-04-17 07:35 UTC, RomuDeuxfois commented on openbas-api/src/main/java/io/openbas/utils/LogUtils.java
> +  public enum LogLevel {
**question:** Why are you not using the java.util.logging.Level enum ?

2025-04-17 07:35 UTC, RomuDeuxfois commented on openbas-api/src/main/java/io/openbas/rest/log/LogApi.java
> +    if (bucket.tryConsume(1)) {
**question:** Why using bucket here ? I don't understand how is usefull.

2025-04-22 07:12 UTC, damgouj commented on openbas-api/src/main/java/io/openbas/rest/log/LogApi.java
> +    if (bucket.tryConsume(1)) {
Sorry, it was a test for the rate limit we have to discuss with @savacano28, I put the PR as draft

2025-04-29 10:03 UTC, antoinemzs requested changes
> Attention: Patch coverage is 8.00000% with 23 lines in your changes missing coverage. Please review.

I'm sure we can go a bit higher than that. Can this never fall over? There are two documented possible outcomes i.e. 200 and 400, ideally we would have tests that trigger both in a few situations :)

2025-05-06 12:06 UTC, merged